[package]
name = "html-to-pdf"
version = "0.1.0"
edition = "2021"

[dependencies]
headless_chrome = "1.0.15"
tokio = { version = "1.28", features = ["full"] }
anyhow = "1.0"
base64 = "0.22.1"
serde = { version = "1.0.216", features = ["derive"] }
serde_json = "1.0.134"

