name: CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache Rust dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Cache Chrome binary
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/chromium
            ./chrome-binary
          key: ${{ runner.os }}-chrome-${{ hashFiles('**/chrome_version.txt') }}

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install Chromium
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser
          chromium-browser --version > chrome_version.txt

      - name: Build and Test
        run: |
          RUST_LOG=info cargo test -- --test-threads=1
        env:
          CHROME_BINARY_PATH: /usr/bin/chromium-browser
