name: Build and Release

on:
  push:
    branches: [master]
    tags:
      - "v*"
  pull_request:
    branches: [master]
    paths-ignore:
      - "**.md"
      - "docs/**"
      - ".gitignore"

jobs:
  release:
    name: Build and Release
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-gnu
          override: true

      - name: Build Release Binary
        run: |
          cargo build --release --target x86_64-unknown-linux-gnu

      - name: Prepare Release Package
        run: |
          mkdir -p release
          cp target/x86_64-unknown-linux-gnu/release/pdf_service release/
          cp README.md release/ || true
          cp LICENSE release/ || true
          cd release
          tar czf ../pdf_service_linux_amd64.tar.gz *

      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          files: pdf_service_linux_amd64.tar.gz
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    name: Deploy to Production
    needs: [release]
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            whoami && pwd
            /opt/pdf_service/update.sh

  build:
    name: Build Latest
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-gnu
          override: true

      - name: Build
        run: cargo build --release --target x86_64-unknown-linux-gnu

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: pdf_service
          path: target/x86_64-unknown-linux-gnu/release/pdf_service
